name: Workflow Dispatch Choice Input Example

on:
  workflow_dispatch:
    inputs:
      color:
        description: 'The color to deploy to'
        required: true
        default: 'blue'
        type: choice
        options:
        - blue
        - green
        - yellow        

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.color }} environment"
